spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://kakaopay.crgicqck2wfs.ap-northeast-2.rds.amazonaws.com:3306/kakao?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: admin
    password: konan415!
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
logging:
  level:
    root: info
    com.zaxxer.hikari.HikariConfig: debug
    org.hibernate.SQL: debug
    hibernate.type.descriptor.sql.BasicBinder: trace


